import React,{Component} from 'react';
import PersonalitySunburstChart from './sunburst-chart/charts/v3-d3v4';
import './SunburstChart.css';

export default class SunburstChart extends Component{
    componentDidMount(){
        var chart = new PersonalitySunburstChart({
            element : this.sunburstChart,
            version : 'v3'
        });
        let value = {  
            "word_count":374,
            "word_count_message":"There were 374 words in the input. We need a minimum of 600, preferably 1,200 or more, to compute statistically significant estimates",
            "processed_language":"en",
            "personality":[  
               {  
                  "trait_id":"big5_openness",
                  "name":"Openness",
                  "category":"personality",
                  "percentile":0.9657183545762622,
                  "raw_score":0.8067996240461678,
                  "significant":true,
                  "children":[  
                     {  
                        "trait_id":"facet_adventurousness",
                        "name":"Adventurousness",
                        "category":"personality",
                        "percentile":0.6985345058300083,
                        "raw_score":0.5233187713729391,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_artistic_interests",
                        "name":"Artistic interests",
                        "category":"personality",
                        "percentile":0.6287949725386448,
                        "raw_score":0.6819627994492102,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_emotionality",
                        "name":"Emotionality",
                        "category":"personality",
                        "percentile":0.596328358149536,
                        "raw_score":0.6581367328308517,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_imagination",
                        "name":"Imagination",
                        "category":"personality",
                        "percentile":0.8423577229826543,
                        "raw_score":0.7847374766616553,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_intellect",
                        "name":"Intellect",
                        "category":"personality",
                        "percentile":0.9981692209370825,
                        "raw_score":0.7417538774398941,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_liberalism",
                        "name":"Authority-challenging",
                        "category":"personality",
                        "percentile":0.9712819697876317,
                        "raw_score":0.6119245631626377,
                        "significant":true
                     }
                  ]
               },
               {  
                  "trait_id":"big5_conscientiousness",
                  "name":"Conscientiousness",
                  "category":"personality",
                  "percentile":0.5705067756560259,
                  "raw_score":0.6363374292074604,
                  "significant":true,
                  "children":[  
                     {  
                        "trait_id":"facet_achievement_striving",
                        "name":"Achievement striving",
                        "category":"personality",
                        "percentile":0.9258878800762781,
                        "raw_score":0.764947267324616,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_cautiousness",
                        "name":"Cautiousness",
                        "category":"personality",
                        "percentile":0.46595653753446026,
                        "raw_score":0.48708032357814907,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_dutifulness",
                        "name":"Dutifulness",
                        "category":"personality",
                        "percentile":0.5371744224002964,
                        "raw_score":0.661185708540448,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_orderliness",
                        "name":"Orderliness",
                        "category":"personality",
                        "percentile":0.06630828607012851,
                        "raw_score":0.44489566203547015,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_self_discipline",
                        "name":"Self-discipline",
                        "category":"personality",
                        "percentile":0.40589863042674046,
                        "raw_score":0.5593108944934746,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_self_efficacy",
                        "name":"Self-efficacy",
                        "category":"personality",
                        "percentile":0.9492444243785225,
                        "raw_score":0.8106901691927971,
                        "significant":true
                     }
                  ]
               },
               {  
                  "trait_id":"big5_extraversion",
                  "name":"Extraversion",
                  "category":"personality",
                  "percentile":0.8110050624396207,
                  "raw_score":0.5903465593378889,
                  "significant":true,
                  "children":[  
                     {  
                        "trait_id":"facet_activity_level",
                        "name":"Activity level",
                        "category":"personality",
                        "percentile":0.9797072670073639,
                        "raw_score":0.6451598233043337,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_assertiveness",
                        "name":"Assertiveness",
                        "category":"personality",
                        "percentile":0.9613613889330943,
                        "raw_score":0.73237693610472,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_cheerfulness",
                        "name":"Cheerfulness",
                        "category":"personality",
                        "percentile":0.44590369377734,
                        "raw_score":0.6135736942413506,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_excitement_seeking",
                        "name":"Excitement-seeking",
                        "category":"personality",
                        "percentile":0.6075910813151655,
                        "raw_score":0.6151815030011775,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_friendliness",
                        "name":"Outgoing",
                        "category":"personality",
                        "percentile":0.48926755594622495,
                        "raw_score":0.5591391810806537,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_gregariousness",
                        "name":"Gregariousness",
                        "category":"personality",
                        "percentile":0.18184296308759612,
                        "raw_score":0.4066439968071173,
                        "significant":true
                     }
                  ]
               },
               {  
                  "trait_id":"big5_agreeableness",
                  "name":"Agreeableness",
                  "category":"personality",
                  "percentile":0.4054100813068055,
                  "raw_score":0.7326824602697383,
                  "significant":true,
                  "children":[  
                     {  
                        "trait_id":"facet_altruism",
                        "name":"Altruism",
                        "category":"personality",
                        "percentile":0.7358183622069151,
                        "raw_score":0.7272081632014016,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_cooperation",
                        "name":"Cooperation",
                        "category":"personality",
                        "percentile":0.4760729853270886,
                        "raw_score":0.5757735087985925,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_modesty",
                        "name":"Modesty",
                        "category":"personality",
                        "percentile":0.018956919483732626,
                        "raw_score":0.3388435136910373,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_morality",
                        "name":"Uncompromising",
                        "category":"personality",
                        "percentile":0.3967142312671055,
                        "raw_score":0.6134552293108384,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_sympathy",
                        "name":"Sympathy",
                        "category":"personality",
                        "percentile":0.8739311244081183,
                        "raw_score":0.707205938501057,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_trust",
                        "name":"Trust",
                        "category":"personality",
                        "percentile":0.9656604121659559,
                        "raw_score":0.6608023235841114,
                        "significant":true
                     }
                  ]
               },
               {  
                  "trait_id":"big5_neuroticism",
                  "name":"Emotional range",
                  "category":"personality",
                  "percentile":0.6678710097087786,
                  "raw_score":0.49183349268186133,
                  "significant":true,
                  "children":[  
                     {  
                        "trait_id":"facet_anger",
                        "name":"Fiery",
                        "category":"personality",
                        "percentile":0.39636237223976684,
                        "raw_score":0.5213455514892467,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_anxiety",
                        "name":"Prone to worry",
                        "category":"personality",
                        "percentile":0.2948679031630608,
                        "raw_score":0.5573387303794055,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_depression",
                        "name":"Melancholy",
                        "category":"personality",
                        "percentile":0.4640164320282814,
                        "raw_score":0.4427181726960981,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_immoderation",
                        "name":"Immoderation",
                        "category":"personality",
                        "percentile":0.40042688156235773,
                        "raw_score":0.49089740547825506,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_self_consciousness",
                        "name":"Self-consciousness",
                        "category":"personality",
                        "percentile":0.6212996687817844,
                        "raw_score":0.5629684776582328,
                        "significant":true
                     },
                     {  
                        "trait_id":"facet_vulnerability",
                        "name":"Susceptible to stress",
                        "category":"personality",
                        "percentile":0.2965311959940652,
                        "raw_score":0.4335743033813168,
                        "significant":true
                     }
                  ]
               }
            ],
            "needs":[  
               {  
                  "trait_id":"need_challenge",
                  "name":"Challenge",
                  "category":"needs",
                  "percentile":0.8633267498080508,
                  "raw_score":0.7809108560531317,
                  "significant":true
               },
               {  
                  "trait_id":"need_closeness",
                  "name":"Closeness",
                  "category":"needs",
                  "percentile":0.14897418914090377,
                  "raw_score":0.7471615941006605,
                  "significant":true
               },
               {  
                  "trait_id":"need_curiosity",
                  "name":"Curiosity",
                  "category":"needs",
                  "percentile":0.97816129889231,
                  "raw_score":0.8697402685642203,
                  "significant":true
               },
               {  
                  "trait_id":"need_excitement",
                  "name":"Excitement",
                  "category":"needs",
                  "percentile":0.2967799239010496,
                  "raw_score":0.6428114012979103,
                  "significant":true
               },
               {  
                  "trait_id":"need_harmony",
                  "name":"Harmony",
                  "category":"needs",
                  "percentile":0.24332415505805355,
                  "raw_score":0.7852367952745224,
                  "significant":true
               },
               {  
                  "trait_id":"need_ideal",
                  "name":"Ideal",
                  "category":"needs",
                  "percentile":0.5241218622497343,
                  "raw_score":0.6939296730389645,
                  "significant":true
               },
               {  
                  "trait_id":"need_liberty",
                  "name":"Liberty",
                  "category":"needs",
                  "percentile":0.5725734330901038,
                  "raw_score":0.7433645375035627,
                  "significant":true
               },
               {  
                  "trait_id":"need_love",
                  "name":"Love",
                  "category":"needs",
                  "percentile":0.4708853916731029,
                  "raw_score":0.7651065672404698,
                  "significant":true
               },
               {  
                  "trait_id":"need_practicality",
                  "name":"Practicality",
                  "category":"needs",
                  "percentile":0.5714209341714176,
                  "raw_score":0.7316621612900198,
                  "significant":true
               },
               {  
                  "trait_id":"need_self_expression",
                  "name":"Self-expression",
                  "category":"needs",
                  "percentile":0.21284935919714082,
                  "raw_score":0.6475606227687395,
                  "significant":true
               },
               {  
                  "trait_id":"need_stability",
                  "name":"Stability",
                  "category":"needs",
                  "percentile":0.19225016504685905,
                  "raw_score":0.7067537795231134,
                  "significant":true
               },
               {  
                  "trait_id":"need_structure",
                  "name":"Structure",
                  "category":"needs",
                  "percentile":0.921544841329555,
                  "raw_score":0.7344352555142806,
                  "significant":true
               }
            ],
            "values":[  
               {  
                  "trait_id":"value_conservation",
                  "name":"Conservation",
                  "category":"values",
                  "percentile":0.15952943866586938,
                  "raw_score":0.6205620917507617,
                  "significant":true
               },
               {  
                  "trait_id":"value_openness_to_change",
                  "name":"Openness to change",
                  "category":"values",
                  "percentile":0.838432198547976,
                  "raw_score":0.8223680230091295,
                  "significant":true
               },
               {  
                  "trait_id":"value_hedonism",
                  "name":"Hedonism",
                  "category":"values",
                  "percentile":0.1161927727872128,
                  "raw_score":0.6618811042155143,
                  "significant":true
               },
               {  
                  "trait_id":"value_self_enhancement",
                  "name":"Self-enhancement",
                  "category":"values",
                  "percentile":0.3766995831753905,
                  "raw_score":0.6925478783192722,
                  "significant":true
               },
               {  
                  "trait_id":"value_self_transcendence",
                  "name":"Self-transcendence",
                  "category":"values",
                  "percentile":0.674474124222577,
                  "raw_score":0.8403257411090368,
                  "significant":true
               }
            ],
            "warnings":[  
               {  
                  "warning_id":"WORD_COUNT_MESSAGE",
                  "message":"There were 374 words in the input. We need a minimum of 600, preferably 1,200 or more, to compute statistically significant estimates"
               }
            ]
         };
        chart.show(value, 'https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png');
    }
    render(){
        return (
            <div ref={elem => (this.sunburstChart = elem)}>
            </div>
        );
    }
}